// Generated by CoffeeScript 1.7.1
var Gioco;

Gioco = (function() {
  function Gioco(token) {
    this.options = {
      url: 'http://localhost:3000/api',
      headers: {
        token: token
      }
    };
  }

  Gioco.prototype.getResource = function(aid) {
    var params;
    params = {
      url: '/resource/get_resource.json',
      type: 'GET'
    };
    return this.sendRequest(params, aid);
  };

  Gioco.prototype.addBagde = function(name, aid) {
    var params;
    params = {
      url: '/resource/add_badge.json',
      type: 'POST',
      data: {
        badge: {
          name: name
        }
      }
    };
    return this.sendRequest(params, aid);
  };

  Gioco.prototype.removeBagde = function(name, aid) {
    var params;
    params = {
      url: '/resource/remove_badge.json',
      type: 'delete',
      data: {
        badge: {
          name: name
        }
      }
    };
    return this.sendRequest(params, aid);
  };

  Gioco.prototype.addPoints = function(points, aid) {
    var params;
    params = {
      url: '/resource/add_points.json',
      type: 'POST',
      data: {
        points: points
      }
    };
    return this.sendRequest(params, aid);
  };

  Gioco.prototype.removePoints = function(points, aid) {
    var params;
    params = {
      url: '/resource/remove_points.json',
      type: 'delete',
      data: {
        points: points
      }
    };
    return this.sendRequest(params, aid);
  };

  Gioco.prototype.addLevel = function(levels, aid) {
    var params;
    params = {
      url: '/resource/add_level.json',
      type: 'POST',
      data: {
        levels: levels
      }
    };
    return this.sendRequest(params, aid);
  };

  Gioco.prototype.removeLevel = function(levels, aid) {
    var params;
    params = {
      url: '/resource/remove_level.json',
      type: 'delete',
      data: {
        levels: levels
      }
    };
    return this.sendRequest(params, aid);
  };

  Gioco.prototype.mountResourceRequest = function(data, aid) {
    data = data === void 0 ? {} : data;
    data.resource = {
      aid: aid
    };
    return data;
  };

  Gioco.prototype.sendRequest = function(params, aid) {
    params.url = this.options.url + params.url;
    params.data = this.mountResourceRequest(params.data, aid);
    params.headers = {
      Token: this.options.headers.token
    };
    return $.ajax(params);
  };

  return Gioco;

})();
